project:
  type: website

website:
  title: "Cohort Analytics ver.1"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Cohort
        menu: 
          - href: daily.qmd
            text: Cohort Daily
          - href: weekly.qmd
            text: Cohort Weekly
          - href: monthly.qmd
            text: Cohort Monthly
      - href: feature.qmd
        text: Feature Log

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

