project:
  type: website

website:
  title: "Report & Analytics Web ver.1"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Cohort
        menu: 
          - href: daily.qmd
            text: Cohort Daily
          - href: weekly.qmd
            text: Cohort Weekly
          - href: monthly.qmd
            text: Cohort Monthly

security:
  oauth2:
    client:
      registration:
        google:
          clientId:
          clientSecret:
          scope:
            - email
            - profile

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

